spring:
  application:
    name: springboardapi
  # DB 연결 정보가 없을 때 임시로 사용한 자동 설정 제외 옵션
  # 필요 시 다시 활성화 할 수 있도록 주석으로 남겨뒀다.
  # autoconfigure:
  # exclude:
  #    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
# JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
